tunnel: a9c9ff21-69cb-4d80-bcaa-f1fc52c178c2
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: main.dockerstack.dpdns.org
    service: http://caddy:80
  - hostname: ttyd.dockerstack.dpdns.org
    service: http://caddy:80
  - hostname: dozzle.dockerstack.dpdns.org
    service: http://caddy:80
  - hostname: files.dockerstack.dpdns.org
    service: http://caddy:80
  - service: http_status:404
